using CB.Core.Entities;
using CB.Infrastructure.Persistance.Configurations;
using Microsoft.EntityFrameworkCore;

namespace CB.Infrastructure.Persistance
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        public DbSet<Role> Roles { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<RolePermission> RolePermissions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Logo> Logos { get; set; }
        public DbSet<Translate> Translates { get; set; }
        public DbSet<TranslateTranslation> TranslateTranslations { get; set; }
        public DbSet<Social> Socials { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<AddressTranslation> AddressTranslations { get; set; }
        public DbSet<Phone> Phones { get; set; }
        public DbSet<PhoneTranslation> PhoneTranslations { get; set; }
        public DbSet<Hero> Heroes { get; set; }
        public DbSet<HeroTranslation> HeroTranslations { get; set; }
        public DbSet<Valute> Valutes { get; set; }
        public DbSet<ValuteTranslation> ValuteTranslations { get; set; }
        public DbSet<Rate> Rates { get; set; }
        public DbSet<PercentCorridorCategory> PercentCorridorCategories { get; set; }
        public DbSet<PercentCorridorCategoryTranslation> PercentCorridorCategoryTranslations { get; set; }
        public DbSet<PercentCorridor> PercentCorridors { get; set; }
        public DbSet<MonetaryIndicatorCategory> MonetaryIndicatorCategories { get; set; }
        public DbSet<MonetaryIndicatorCategoryTranslation> MonetaryIndicatorCategoryTranslations { get; set; }
        public DbSet<MonetaryIndicator> MonetaryIndicators { get; set; }
        public DbSet<BankSectorCategory> BankSectorCategories { get; set; }
        public DbSet<BankSectorCategoryTranslation> BankSectorCategoryTranslations { get; set; }
        public DbSet<BankSector> BankSectors { get; set; }
        public DbSet<BankNoteCategory> BankNoteCategories { get; set; }
        public DbSet<BankNoteCategoryTranslation> BankNoteCategoryTranslations { get; set; }
        public DbSet<BankNote> BankNotes { get; set; }
        public DbSet<Inflation> Inflations { get; set; }
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<BlogImage> BlogImages { get; set; }
        public DbSet<BlogTranslation> BlogTranslations { get; set; }
        public DbSet<Advertisement> Advertisements { get; set; }
        public DbSet<AdvertisementTranslation> AdvertisementTranslations { get; set; }
        public DbSet<Interview> Interviews { get; set; }
        public DbSet<InterviewTranslation> InterviewTranslations { get; set; }
        public DbSet<DigitalPortalCaption> DigitalPortalCaptions { get; set; }
        public DbSet<DigitalPortalCaptionTranslation> DigitalPortalCaptionTranslations { get; set; }
        public DbSet<DigitalPortal> DigitalPortals { get; set; }
        public DbSet<DigitalPortalTranslation> DigitalPortalTranslations { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<GalleryImage> GalleryImages { get; set; }
        public DbSet<GalleryTranslation> GalleryTranslations { get; set; }
        public DbSet<Video> Videos { get; set; }
        public DbSet<VideoTranslation> VideoTranslations { get; set; }
        public DbSet<MacroDocument> MacroDocuments { get; set; }
        public DbSet<MacroDocumentTranslation> MacroDocumentTranslations { get; set; }
        public DbSet<OtherInfo> OtherInfos { get; set; }
        public DbSet<OtherInfoTranslation> OtherInfoTranslations { get; set; }
        public DbSet<About> Abouts { get; set; }
        public DbSet<AboutTranslation> AboutTranslations { get; set; }
        public DbSet<History> Histories { get; set; }
        public DbSet<HistoryTranslation> HistoryTranslations { get; set; }
        public DbSet<Chronology> Chronologies { get; set; }
        public DbSet<ChronologyTranslation> ChronologyTranslations { get; set; }
        public DbSet<MissionCaption> MissionCaptions { get; set; }
        public DbSet<MissionCaptionTranslation> MissionCaptionTranslations { get; set; }
        public DbSet<Mission> Missions { get; set; }
        public DbSet<MissionTranslation> MissionTranslations { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ContactTranslation> ContactTranslations { get; set; }
        public DbSet<Office> Offices { get; set; }
        public DbSet<OfficeTranslation> OfficeTranslations { get; set; }
        public DbSet<FormerChairman> FormerChairmen { get; set; }
        public DbSet<FormerChairmanTranslation> FormerChairmanTranslations { get; set; }
        public DbSet<StructureCaption> StructureCaptions { get; set; }
        public DbSet<Statute> Statutes { get; set; }
        public DbSet<StatuteTranslation> StatuteTranslations { get; set; }
        public DbSet<StructureCaptionTranslation> StructureCaptionTranslations { get; set; }
        public DbSet<Director> Directors { get; set; }
        public DbSet<DirectorTranslation> DirectorTranslations { get; set; }
        public DbSet<DirectorContact> DirectorContacts { get; set; }
        public DbSet<DirectorContactTranslation> DirectorContactTranslations { get; set; }
        public DbSet<DirectorDetail> DirectorDetails { get; set; }
        public DbSet<DirectorDetailTranslation> DirectorDetailTranslations { get; set; }
        public DbSet<Manager> Managers { get; set; }
        public DbSet<ManagerTranslation> ManagerTranslations { get; set; }
        public DbSet<ManagerContact> ManagerContacts { get; set; }
        public DbSet<ManagerContactTranslation> ManagerContactTranslations { get; set; }
        public DbSet<ManagerDetail> ManagerDetails { get; set; }
        public DbSet<ManagerDetailTranslation> ManagerDetailTranslations { get; set; }
        public DbSet<Duration> Durations { get; set; }
        public DbSet<DurationTranslation> DurationTranslations { get; set; }
        public DbSet<YieldCurve> YieldCurves { get; set; }
        public DbSet<YieldDuration> YieldDurations { get; set; }
        public DbSet<YieldParameter> YieldParameters { get; set; }
        public DbSet<StatisticCaption> StatisticCaptions { get; set; }
        public DbSet<StatisticCaptionTranslation> StatisticCaptionTranslations { get; set; }
        public DbSet<StatisticalBulletin> StatisticalBulletins { get; set; }
        public DbSet<StatisticalBulletinTranslation> StatisticalBulletinTranslations { get; set; }
        public DbSet<StatisticalReport> StatisticalReports { get; set; }
        public DbSet<StatisticalReportTranslation> StatisticalReportTranslations { get; set; }
        public DbSet<StatisticalReportFile> StatisticalReportFiles { get; set; }
        public DbSet<StatisticalReportFileTranslation> StatisticalReportFileTranslations { get; set; }
        public DbSet<RevisionPolicy> RevisionPolicies { get; set; }
        public DbSet<RevisionPolicyTranslation> RevisionPolicyTranslations { get; set; }
        public DbSet<Methodology> Methodologies { get; set; }
        public DbSet<MethodologyTranslation> MethodologyTranslations { get; set; }
        public DbSet<LegalAct> LegalActs { get; set; }
        public DbSet<LegalActTranslation> LegalActTranslations { get; set; }
        public DbSet<InsurerCaption> InsurerCaptions { get; set; }
        public DbSet<InsurerCaptionTranslation> InsurerCaptionTranslations { get; set; }
        public DbSet<InsurerFile> InsurerFiles { get; set; }
        public DbSet<InsurerFileTranslation> InsurerFileTranslations { get; set; }
        public DbSet<Insurer> Insurers { get; set; }
        public DbSet<InsurerTranslation> InsurerTranslations { get; set; }
        public DbSet<BankCaption> BankCaptions { get; set; }
        public DbSet<BankCaptionTranslation> BankCaptionTranslations { get; set; }
        public DbSet<BankFile> BankFiles { get; set; }
        public DbSet<BankFileTranslation> BankFileTranslations { get; set; }
        public DbSet<Bank> Banks { get; set; }
        public DbSet<BankTranslation> BankTranslations { get; set; }
        public DbSet<OperatorBankCaption> OperatorBankCaptions { get; set; }
        public DbSet<OperatorBankCaptionTranslation> OperatorBankCaptionTranslations { get; set; }
        public DbSet<OperatorBank> OperatorBanks { get; set; }
        public DbSet<OperatorBankTranslation> OperatorBankTranslations { get; set; }
        public DbSet<CreditUnionCaption> CreditUnionCaptions { get; set; }
        public DbSet<CreditUnionCaptionTranslation> CreditUnionCaptionTranslations { get; set; }
        public DbSet<CreditUnion> CreditUnions { get; set; }
        public DbSet<CreditUnionTranslation> CreditUnionTranslations { get; set; }
        public DbSet<PaymentAgentCaption> PaymentAgentCaptions { get; set; }
        public DbSet<PaymentAgentCaptionTranslation> PaymentAgentCaptionTranslations { get; set; }
        public DbSet<PaymentAgentFile> PaymentAgentFiles { get; set; }
        public DbSet<PaymentAgentFileTranslation> PaymentAgentFileTranslations { get; set; }
        public DbSet<RegistrationSecurityCaption> RegistrationSecurityCaptions { get; set; }
        public DbSet<RegistrationSecurityCaptionTranslation> RegistrationSecurityCaptionTranslations { get; set; }
        public DbSet<RegistrationSecurity> RegistrationSecurities { get; set; }
        public DbSet<RegistrationSecurityTranslation> RegistrationSecurityTranslations { get; set; }
        public DbSet<ShareholderCaption> ShareholderCaptions { get; set; }
        public DbSet<ShareholderCaptionTranslation> ShareholderCaptionTranslations { get; set; }
        public DbSet<ControlMeasureCategory> ControlMeasureCategories { get; set; }
        public DbSet<ControlMeasureCategoryTranslation> ControlMeasureCategoryTranslations { get; set; }
        public DbSet<ControlMeasure> ControlMeasures { get; set; }
        public DbSet<ControlMeasureTranslation> ControlMeasureTranslations { get; set; }
        public DbSet<MonetaryPolicyCaption> MonetaryPolicyCaptions { get; set; }
        public DbSet<MonetaryPolicyCaptionTranslation> MonetaryPolicyCaptionTranslations { get; set; }
        public DbSet<MonetaryPolicyDirection> MonetaryPolicyDirections { get; set; }
        public DbSet<MonetaryPolicyDirectionTranslation> MonetaryPolicyDirectionTranslations { get; set; }
        public DbSet<MonetaryPolicyDecision> MonetaryPolicyDecisions { get; set; }
        public DbSet<MonetaryPolicyDecisionTranslation> MonetaryPolicyDecisionTranslations { get; set; }
        public DbSet<MonetaryPolicyReview> MonetaryPolicyReviews { get; set; }
        public DbSet<MonetaryPolicyReviewTranslation> MonetaryPolicyReviewTranslations { get; set; }
        public DbSet<MonetaryPolicyVideo> MonetaryPolicyVideos { get; set; }
        public DbSet<MonetaryPolicyGraphic> MonetaryPolicyGraphics { get; set; }
        public DbSet<MonetaryPolicyGraphicTranslation> MonetaryPolicyGraphicTranslations { get; set; }
        public DbSet<Poster> Posters { get; set; }
        public DbSet<PolicyAnalysis> PolicyAnalysises { get; set; }
        public DbSet<PolicyAnalysisTranslation> PolicyAnalysisTranslations { get; set; }
        public DbSet<PolicyAnalysisFile> PolicyAnalysisFiles { get; set; }
        public DbSet<PolicyAnalysisFileTranslation> PolicyAnalysisFileTranslations { get; set; }
        public DbSet<MonetaryPolicyInstrument> MonetaryPolicyInstruments { get; set; }
        public DbSet<MonetaryPolicyInstrumentTranslation> MonetaryPolicyInstrumentTranslations { get; set; }
        public DbSet<MediaCaption> MediaCaptions { get; set; }
        public DbSet<MediaCaptionTranslation> MediaCaptionTranslations { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventTranslation> EventTranslations { get; set; }
        public DbSet<EventContent> EventContents { get; set; }
        public DbSet<EventContentTranslation> EventContentTranslations { get; set; }
        public DbSet<EventContentImage> EventContentImages { get; set; }
        public DbSet<EventMedia> EventMedias { get; set; }
        public DbSet<FutureEvent> FutureEvents { get; set; }
        public DbSet<FutureEventTranslation> FutureEventTranslations { get; set; }
        public DbSet<MediaQuery> MediaQueries { get; set; }
        public DbSet<MediaQueryTranslation> MediaQueryTranslations { get; set; }
        public DbSet<CBAR105Caption> CBAR105Captions { get; set; }
        public DbSet<CBAR105CaptionTranslation> CBAR105CaptionTranslations { get; set; }
        public DbSet<CBAR105Event> CBAR105Events { get; set; }
        public DbSet<CBAR105EventTranslation> CBAR105EventTranslations { get; set; }
        public DbSet<CBAR105EventImage> CBAR105EventImages { get; set; }
        public DbSet<PresidentDecree> PresidentDecrees { get; set; }
        public DbSet<PresidentDecreeTranslation> PresidentDecreeTranslations { get; set; }
        public DbSet<DevelopmentArticle> DevelopmentArticles { get; set; }
        public DbSet<DevelopmentArticleTranslation> DevelopmentArticleTranslations { get; set; }
        public DbSet<AnniversaryStamp> AnniversaryStamps { get; set; }
        public DbSet<AnniversaryStampTranslation> AnniversaryStampTranslations { get; set; }
        public DbSet<AnniversaryCoin> AnniversaryCoins { get; set; }
        public DbSet<AnniversaryCoinTranslation> AnniversaryCoinTranslations { get; set; }
        public DbSet<TrainingJournalist> TrainingJournalists { get; set; }
        public DbSet<TrainingJournalistTranslation> TrainingJournalistTranslations { get; set; }
        public DbSet<TrainingJournalistImage> TrainingJournalistImages { get; set; }
        public DbSet<CBAR100Gallery> CBAR100Galleries { get; set; }
        public DbSet<CBAR100Video> CBAR100Videos { get; set; }
        public DbSet<CBAR100VideoTranslation> CBAR100VideoTranslations { get; set; }
        public DbSet<CareerCaption> CareerCaptions { get; set; }
        public DbSet<CareerCaptionTranslation> CareerCaptionTranslations { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<DepartmentTranslation> DepartmentTranslations { get; set; }
        public DbSet<Branch> Branches { get; set; }
        public DbSet<BranchTranslation> BranchTranslations { get; set; }
        public DbSet<Position> Positions { get; set; }
        public DbSet<PositionTranslation> PositionTranslations { get; set; }
        public DbSet<Vacancy> Vacancies { get; set; }
        public DbSet<VacancyTranslation> VacancyTranslations { get; set; }
        public DbSet<VacancyDetail> VacancyDetails { get; set; }
        public DbSet<VacancyDetailTranslation> VacancyDetailTranslations { get; set; }
        public DbSet<InternshipCaption> InternshipCaptions { get; set; }
        public DbSet<InternshipCaptionTranslation> InternshipCaptionTranslations { get; set; }
        public DbSet<InternshipDirection> InternshipDirections { get; set; }
        public DbSet<InternshipDirectionTranslation> InternshipDirectionTranslations { get; set; }
        public DbSet<InternshipProgram> InternshipPrograms { get; set; }
        public DbSet<InternshipProgramTranslation> InternshipProgramTranslations { get; set; }
        public DbSet<Volunteer> Volunteers { get; set; }
        public DbSet<VolunteerTranslation> VolunteerTranslations { get; set; }
        public DbSet<NakhchivanBulletin> NakhchivanBulletins { get; set; }
        public DbSet<NakhchivanBulletinTranslation> NakhchivanBulletinTranslations { get; set; }
        public DbSet<NakhchivanPublication> NakhchivanPublications { get; set; }
        public DbSet<NakhchivanPublicationTranslation> NakhchivanPublicationTranslations { get; set; }
        public DbSet<NakhchivanBlog> NakhchivanBlogs { get; set; }
        public DbSet<NakhchivanBlogTranslation> NakhchivanBlogTranslations { get; set; }
        public DbSet<NakhchivanEvent> NakhchivanEvents { get; set; }
        public DbSet<NakhchivanEventTranslation> NakhchivanEventTranslations { get; set; }
        public DbSet<NakhchivanContact> NakhchivanContacts { get; set; }
        public DbSet<NakhchivanContactTranslation> NakhchivanContactTranslations { get; set; }
        public DbSet<FinancialDevelopment> FinancialDevelopments { get; set; }
        public DbSet<FinancialDevelopmentTranslation> FinancialDevelopmentTranslations { get; set; }
        public DbSet<CustomerRightCaption> CustomerRightCaptions { get; set; }
        public DbSet<CustomerRightCaptionTranslation> CustomerRightCaptionTranslations { get; set; }
        public DbSet<CitizenApplicationCategory> CitizenApplicationCategories { get; set; }
        public DbSet<CitizenApplicationCategoryTranslation> CitizenApplicationCategoryTranslations { get; set; }
        public DbSet<CitizenApplication> CitizenApplications { get; set; }
        public DbSet<Infographic> Infographics { get; set; }
        public DbSet<InfographicTranslation> InfographicTranslations { get; set; }
        public DbSet<ComplaintIndexCategory> ComplaintIndexCategories { get; set; }
        public DbSet<ComplaintIndexCategoryTranslation> ComplaintIndexCategoryTranslations { get; set; }
        public DbSet<ComplaintIndex> ComplaintIndices { get; set; }
        public DbSet<ComplaintIndexTranslation> ComplaintIndexTranslations { get; set; }
        public DbSet<CustomerEvent> CustomerEvents { get; set; }
        public DbSet<CustomerEventTranslation> CustomerEventTranslations { get; set; }
        public DbSet<CustomerDocument> CustomerDocuments { get; set; }
        public DbSet<CustomerDocumentTranslation> CustomerDocumentTranslations { get; set; }
        public DbSet<PaymentService> PaymentServices { get; set; }
        public DbSet<PaymentServiceTranslation> PaymentServiceTranslations { get; set; }
        public DbSet<InformationBulletin> InformationBulletins { get; set; }
        public DbSet<InformationBulletinTranslation> InformationBulletinTranslations { get; set; }
        public DbSet<ReviewApplication> ReviewApplications { get; set; }
        public DbSet<ReviewApplicationTranslation> ReviewApplicationTranslations { get; set; }
        public DbSet<ReviewApplicationFile> ReviewApplicationFiles { get; set; }
        public DbSet<ReviewApplicationFileTranslation> ReviewApplicationFileTranslations { get; set; }
        public DbSet<ReviewApplicationLink> ReviewApplicationLinks { get; set; }
        public DbSet<ReviewApplicationLinkTranslation> ReviewApplicationLinkTranslations { get; set; }
        public DbSet<ReviewApplicationVideo> ReviewApplicationVideos { get; set; }
        public DbSet<ReviewApplicationVideoTranslation> ReviewApplicationVideoTranslations { get; set; }
        public DbSet<ReceptionCitizenCategory> ReceptionCitizenCategories { get; set; }
        public DbSet<ReceptionCitizenCategoryTranslation> ReceptionCitizenCategoryTranslations { get; set; }
        public DbSet<ReceptionCitizen> ReceptionCitizens { get; set; }
        public DbSet<ReceptionCitizenTranslation> ReceptionCitizenTranslations { get; set; }
        public DbSet<ReceptionCitizenFile> ReceptionCitizenFiles { get; set; }
        public DbSet<ReceptionCitizenFileTranslation> ReceptionCitizenFileTranslations { get; set; }
        public DbSet<ReceptionCitizenLink> ReceptionCitizenLinks { get; set; }
        public DbSet<ReceptionCitizenLinkTranslation> ReceptionCitizenLinkTranslations { get; set; }
        public DbSet<ReceptionCitizenVideo> ReceptionCitizenVideos { get; set; }
        public DbSet<CustomerContact> CustomerContacts { get; set; }
        public DbSet<CustomerContactTranslation> CustomerContactTranslations { get; set; }
        public DbSet<CustomerFeedbackCaption> CustomerFeedbackCaptions { get; set; }
        public DbSet<CustomerFeedbackCaptionTranslation> CustomerFeedbackCaptionTranslations { get; set; }
        public DbSet<CustomerFeedback> CustomerFeedbacks { get; set; }
        public DbSet<CustomerFeedbackTranslation> CustomerFeedbackTranslations { get; set; }
        public DbSet<CustomerProposal> CustomerProposals { get; set; }
        public DbSet<CustomerProposalTranslation> CustomerProposalTranslations { get; set; }
        public DbSet<TerritorialOffice> TerritorialOffices { get; set; }
        public DbSet<TerritorialOfficeTranslation> TerritorialOfficeTranslations { get; set; }
        public DbSet<TerritorialOfficeRegion> TerritorialOfficeRegions { get; set; }
        public DbSet<TerritorialOfficeRegionTranslation> TerritorialOfficeRegionTranslations { get; set; }
        public DbSet<TerritorialOfficeStatistic> TerritorialOfficeStatistics { get; set; }
        public DbSet<TerritorialOfficeStatisticTranslation> TerritorialOfficeStatisticTranslations { get; set; }
        public DbSet<CustomerDocumentFile> CustomerDocumentFiles { get; set; }
        public DbSet<CustomerDocumentFileTranslation> CustomerDocumentFileTranslations { get; set; }
        public DbSet<FraudStatisticCaption> FraudStatisticCaptions { get; set; }
        public DbSet<FraudStatisticCaptionTranslation> FraudStatisticCaptionTranslations { get; set; }
        public DbSet<FraudStatistic> FraudStatistics { get; set; }
        public DbSet<FraudStatisticTranslation> FraudStatisticTranslations { get; set; }
        public DbSet<ExecutionStatus> ExecutionStatuses { get; set; }
        public DbSet<ExecutionStatusTranslation> ExecutionStatusTranslations { get; set; }
        public DbSet<PaymentSystemCaption> PaymentSystemCaptions { get; set; }
        public DbSet<PaymentSystemCaptionTranslation> PaymentSystemCaptionTranslations { get; set; }
        public DbSet<RealTimeSettlementSystem> RealTimeSettlementSystems { get; set; }
        public DbSet<RealTimeSettlementSystemTranslation> RealTimeSettlementSystemTranslations { get; set; }
        public DbSet<CorrespondentAccount> CorrespondentAccounts { get; set; }
        public DbSet<CorrespondentAccountTranslation> CorrespondentAccountTranslations { get; set; }
        public DbSet<TechnicalDocument> TechnicalDocuments { get; set; }
        public DbSet<TechnicalDocumentTranslation> TechnicalDocumentTranslations { get; set; }
        public DbSet<Software> Softwares { get; set; }
        public DbSet<SoftwareTranslation> SoftwareTranslations { get; set; }
        public DbSet<InstantPaymentSystem> InstantPaymentSystems { get; set; }
        public DbSet<InstantPaymentSystemTranslation> InstantPaymentSystemTranslations { get; set; }
        public DbSet<InstantPaymentPost> InstantPaymentPosts { get; set; }
        public DbSet<InstantPaymentPostTranslation> InstantPaymentPostTranslations { get; set; }
        public DbSet<InstantPaymentOrganization> InstantPaymentOrganizations { get; set; }
        public DbSet<InstantPaymentOrganizationTranslation> InstantPaymentOrganizationTranslations { get; set; }
        public DbSet<InstantPaymentFAQTranslation> InstantPaymentFAQTranslations { get; set; }
        public DbSet<Regulation> Regulations { get; set; }
        public DbSet<RegulationTranslation> RegulationTranslations { get; set; }
        public DbSet<Tariff> Tariffs { get; set; }
        public DbSet<TariffTranslation> TariffTranslations { get; set; }
        public DbSet<ParticipantCategory> ParticipantCategories { get; set; }
        public DbSet<ParticipantCategoryTranslation> ParticipantCategoryTranslations { get; set; }
        public DbSet<Participant> Participants { get; set; }
        public DbSet<ParticipantTranslation> ParticipantTranslations { get; set; }
        public DbSet<PaymentSystemStandart> PaymentSystemStandarts { get; set; }
        public DbSet<PaymentSystemStandartTranslation> PaymentSystemStandartTranslations { get; set; }
        public DbSet<PaymentSystemStandartFile> PaymentSystemStandartFiles { get; set; }
        public DbSet<PaymentSystemStandartFileTranslation> PaymentSystemStandartFileTranslations { get; set; }
        public DbSet<PaymentSystemStandartFAQ> PaymentSystemStandartFAQs { get; set; }
        public DbSet<PaymentSystemStandartFAQTranslation> PaymentSystemStandartFAQTranslations { get; set; }
        public DbSet<StateProgramCaption> StateProgramCaptions { get; set; }
        public DbSet<StateProgramCaptionTranslation> StateProgramCaptionTranslations { get; set; }
        public DbSet<StateProgramCategory> StateProgramCategories { get; set; }
        public DbSet<StateProgramCategoryTranslation> StateProgramCategoryTranslations { get; set; }
        public DbSet<StateProgram> StatePrograms { get; set; }
        public DbSet<StateProgramTranslation> StateProgramTranslations { get; set; }
        public DbSet<DigitalPayment> DigitalPayments { get; set; }
        public DbSet<DigitalPaymentTranslation> DigitalPaymentTranslations { get; set; }
        public DbSet<NominationCaption> NominationCaptions { get; set; }
        public DbSet<NominationCaptionTranslation> NominationCaptionTranslations { get; set; }
        public DbSet<NominationCategory> NominationCategories { get; set; }
        public DbSet<NominationCategoryTranslation> NominationCategoryTranslations { get; set; }
        public DbSet<Nomination> Nominations { get; set; }
        public DbSet<NominationTranslation> NominationTranslations { get; set; }
        public DbSet<Lottery> Lotteries { get; set; }
        public DbSet<LotteryTranslation> LotteryTranslations { get; set; }
        public DbSet<LotteryFile> LotteryFiles { get; set; }
        public DbSet<LotteryFileTranslation> LotteryFileTranslations { get; set; }
        public DbSet<LotteryVideo> LotteryVideos { get; set; }
        public DbSet<LotteryVideoTranslation> LotteryVideoTranslations { get; set; }
        public DbSet<LotteryFAQ> LotteryFAQs { get; set; }
        public DbSet<LotteryFAQTranslation> LotteryFAQTranslations { get; set; }
        public DbSet<PaymentSystemControlFile> PaymentSystemControlFiles { get; set; }
        public DbSet<PaymentSystemControlFileTranslation> PaymentSystemControlFileTranslations { get; set; }
        public DbSet<PaymentSystemControl> PaymentSystemControls { get; set; }
        public DbSet<PaymentSystemControlTranslation> PaymentSystemControlTranslations { get; set; }
        public DbSet<PaymentSystemControlService> PaymentSystemControlServices { get; set; }
        public DbSet<PaymentSystemControlServiceTranslation> PaymentSystemControlServiceTranslations { get; set; }
        public DbSet<DigitalPaymentReview> DigitalPaymentReviews { get; set; }
        public DbSet<DigitalPaymentReviewTranslation> DigitalPaymentReviewTranslations { get; set; }
        public DbSet<RealTimeSettlementSystemCaption> RealTimeSettlementSystemCaptions { get; set; }
        public DbSet<RealTimeSettlementSystemCaptionTranslation> RealTimeSettlementSystemCaptionTranslations { get; set; }
        public DbSet<RealTimeSettlementSystemFile> RealTimeSettlementSystemFiles { get; set; }
        public DbSet<RealTimeSettlementSystemFileTranslation> RealTimeSettlementSystemFileTranslations { get; set; }
        public DbSet<ClearingSettlementSystemCaption> ClearingSettlementSystemCaptions { get; set; }
        public DbSet<ClearingSettlementSystemCaptionTranslation> ClearingSettlementSystemCaptionTranslations { get; set; }
        public DbSet<ClearingSettlementSystem> ClearingSettlementSystems { get; set; }
        public DbSet<ClearingSettlementSystemTranslation> ClearingSettlementSystemTranslations { get; set; }
        public DbSet<ClearingSettlementSystemFile> ClearingSettlementSystemFiles { get; set; }
        public DbSet<ClearingSettlementSystemFileTranslation> ClearingSettlementSystemFileTranslations { get; set; }
        public DbSet<InterbankCardCenter> InterbankCardCenters { get; set; }
        public DbSet<InterbankCardCenterTranslation> InterbankCardCenterTranslations { get; set; }
        public DbSet<GovernmentPaymentPortal> GovernmentPaymentPortals { get; set; }
        public DbSet<GovernmentPaymentPortalTranslation> GovernmentPaymentPortalTranslations { get; set; }
        public DbSet<ProcessingActivity> ProcessingActivities { get; set; }
        public DbSet<ProcessingActivityTranslation> ProcessingActivityTranslations { get; set; }
        public DbSet<DigitalPaymentInfographicCategory> DigitalPaymentInfographicCategories { get; set; }
        public DbSet<DigitalPaymentInfographicCategoryTranslation> DigitalPaymentInfographicCategoryTranslations { get; set; }
        public DbSet<DigitalPaymentInfographic> DigitalPaymentInfographics { get; set; }
        public DbSet<DigitalPaymentInfographicTranslation> DigitalPaymentInfographicTranslations { get; set; }
        public DbSet<DigitalPaymentInfographicItem> DigitalPaymentInfographicItems { get; set; }
        public DbSet<FinancialStabilityCaption> FinancialStabilityCaptions { get; set; }
        public DbSet<FinancialStabilityCaptionTranslation> FinancialStabilityCaptionTranslations { get; set; }
        public DbSet<FinancialStabilityReportCaption> FinancialStabilityReportCaptions { get; set; }
        public DbSet<FinancialStabilityReportCaptionTranslation> FinancialStabilityReportCaptionTranslations { get; set; }
        public DbSet<FinancialStabilityReport> FinancialStabilityReports { get; set; }
        public DbSet<FinancialStabilityReportTranslation> FinancialStabilityReportTranslations { get; set; }
        public DbSet<MacroprudentialPolicyFrameworkCaption> MacroprudentialPolicyFrameworkCaptions { get; set; }
        public DbSet<MacroprudentialPolicyFrameworkCaptionTranslation> MacroprudentialPolicyFrameworkCaptionTranslations { get; set; }
        public DbSet<MacroprudentialPolicyFramework> MacroprudentialPolicyFrameworks { get; set; }
        public DbSet<MacroprudentialPolicyFrameworkTranslation> MacroprudentialPolicyFrameworkTranslations { get; set; }
        public DbSet<FinancialInstitution> FinancialInstitutions { get; set; }
        public DbSet<FinancialInstitutionTranslation> FinancialInstitutionTranslations { get; set; }
        public DbSet<FinancingActivityCaption> FinancingActivityCaptions { get; set; }
        public DbSet<FinancingActivityCaptionTranslation> FinancingActivityCaptionTranslations { get; set; }
        public DbSet<FinancingActivity> FinancingActivities { get; set; }
        public DbSet<FinancingActivityTranslation> FinancingActivityTranslations { get; set; }
        public DbSet<RoadmapSustainableFinance> RoadmapSustainableFinances { get; set; }
        public DbSet<RoadmapSustainableFinanceTranslation> RoadmapSustainableFinanceTranslations { get; set; }
        public DbSet<GreenTaxonomy> GreenTaxonomies { get; set; }
        public DbSet<GreenTaxonomyTranslation> GreenTaxonomyTranslations { get; set; }
        public DbSet<RegulationControl> RegulationControls { get; set; }
        public DbSet<RegulationControlTranslation> RegulationControlTranslations { get; set; }
        public DbSet<Disclosure> Disclosures { get; set; }
        public DbSet<DisclosureTranslation> DisclosureTranslations { get; set; }
        public DbSet<InternationalCooperationInitiative> InternationalCooperationInitiatives { get; set; }
        public DbSet<InternationalCooperationInitiativeTranslation> InternationalCooperationInitiativeTranslations { get; set; }
        public DbSet<FinancialEvent> FinancialEvents { get; set; }
        public DbSet<FinancialEventTranslation> FinancialEventTranslations { get; set; }
        public DbSet<InternationalCooperationCaption> InternationalCooperationCaptions { get; set; }
        public DbSet<InternationalCooperationCaptionTranslation> InternationalCooperationCaptionTranslations { get; set; }
        public DbSet<InternationalFinancialOrganization> InternationalFinancialOrganizations { get; set; }
        public DbSet<InternationalFinancialOrganizationTranslation> InternationalFinancialOrganizationTranslations { get; set; }
        public DbSet<CentralBankCooperationCaption> CentralBankCooperationCaptions { get; set; }
        public DbSet<CentralBankCooperationCaptionTranslation> CentralBankCooperationCaptionTranslations { get; set; }
        public DbSet<CentralBankCooperation> CentralBankCooperations { get; set; }
        public DbSet<CentralBankCooperationTranslation> CentralBankCooperationTranslations { get; set; }
        public DbSet<InternationalEvent> InternationalEvents { get; set; }
        public DbSet<InternationalEventTranslation> InternationalEventTranslations { get; set; }
        public DbSet<InternationalEventImage> InternationalEventImages { get; set; }
        public DbSet<MembershipInternationalOrganization> MembershipInternationalOrganizations { get; set; }
        public DbSet<MembershipInternationalOrganizationTranslation> MembershipInternationalOrganizationTranslations { get; set; }
        public DbSet<MarketPercentDegree> MarketPercentDegrees { get; set; }
        public DbSet<MarketInformation> MarketInformations { get; set; }
        public DbSet<MarketInformationTranslation> MarketInformationTranslations { get; set; }
        public DbSet<IndexPeriodCategory> IndexPeriodCategories { get; set; }
        public DbSet<IndexPeriodCategoryTranslation> IndexPeriodCategoryTranslations { get; set; }
        public DbSet<IndexPeriod> IndexPeriods { get; set; }
        public DbSet<IndexIncreasing> IndexIncreasings { get; set; }
        public DbSet<MethodologyExplain> MethodologyExplains { get; set; }
        public DbSet<MethodologyExplainTranslation> MethodologyExplainTranslations { get; set; }
        public DbSet<OpenBanking> OpenBankings { get; set; }
        public DbSet<OpenBankingTranslation> OpenBankingTranslations { get; set; }
        public DbSet<OpenBankingFile> OpenBankingFiles { get; set; }
        public DbSet<OpenBankingFileTranslation> OpenBankingFileTranslations { get; set; }
        public DbSet<CustomEditingMode> CustomEditingModes { get; set; }
        public DbSet<CustomEditingModeTranslation> CustomEditingModeTranslations { get; set; }
        public DbSet<EKYC> EKYCs { get; set; }
        public DbSet<EKYCTranslation> EKYCTranslations { get; set; }
        public DbSet<VirtualActive> VirtualActives { get; set; }
        public DbSet<VirtualActiveTranslation> VirtualActiveTranslations { get; set; }
        public DbSet<CBDC> CBDCs { get; set; }
        public DbSet<CBDCTranslation> CBDCTranslations { get; set; }
        public DbSet<FinancialLiteracyCaption> FinancialLiteracyCaptions { get; set; }
        public DbSet<FinancialLiteracyCaptionTranslation> FinancialLiteracyCaptionTranslations { get; set; }
        public DbSet<FinancialLiteracyEventCaption> FinancialLiteracyEventCaptions { get; set; }
        public DbSet<FinancialLiteracyEventCaptionTranslation> FinancialLiteracyEventCaptionTranslations { get; set; }
        public DbSet<FinancialLiteracyPortalCaption> FinancialLiteracyPortalCaptions { get; set; }
        public DbSet<FinancialLiteracyPortalCaptionTranslation> FinancialLiteracyPortalCaptionTranslations { get; set; }
        public DbSet<VirtualEducationCaption> VirtualEducationCaptions { get; set; }
        public DbSet<VirtualEducationCaptionTranslation> VirtualEducationCaptionTranslations { get; set; }
        public DbSet<FinancialSearchSystemCaption> FinancialSearchSystemCaptions { get; set; }
        public DbSet<FinancialSearchSystemCaptionTranslation> FinancialSearchSystemCaptionTranslations { get; set; }
        public DbSet<FinancialLiteracyEvent> FinancialLiteracyEvents { get; set; }
        public DbSet<FinancialLiteracyEventTranslation> FinancialLiteracyEventTranslations { get; set; }
        public DbSet<FinancialLiteracyPortal> FinancialLiteracyPortals { get; set; }
        public DbSet<FinancialLiteracyPortalTranslation> FinancialLiteracyPortalTranslations { get; set; }
        public DbSet<FinancialLiteracyPortalImage> FinancialLiteracyPortalImages { get; set; }
        public DbSet<VirtualEducation> VirtualEducations { get; set; }
        public DbSet<VirtualEducationTranslation> VirtualEducationTranslations { get; set; }
        public DbSet<VirtualEducationImage> VirtualEducationImages { get; set; }
        public DbSet<FinancialSearchSystem> FinancialSearchSystems { get; set; }
        public DbSet<FinancialSearchSystemTranslation> FinancialSearchSystemTranslations { get; set; }
        public DbSet<FinancialSearchSystemImage> FinancialSearchSystemImages { get; set; }
        public DbSet<PublicationCaption> PublicationCaptions { get; set; }
        public DbSet<PublicationCaptionTranslation> PublicationCaptionTranslations { get; set; }
        public DbSet<EconometricModel> EconometricModels { get; set; }
        public DbSet<EconometricModelTranslation> EconometricModelTranslations { get; set; }
        public DbSet<EconometricModelFile> EconometricModelFiles { get; set; }
        public DbSet<EconometricModelFileTranslation> EconometricModelFileTranslations { get; set; }
        public DbSet<StaffArticleCaption> StaffArticleCaptions { get; set; }
        public DbSet<StaffArticleCaptionTranslation> StaffArticleCaptionTranslations { get; set; }
        public DbSet<StaffArticle> StaffArticles { get; set; }
        public DbSet<StaffArticleTranslation> StaffArticleTranslations { get; set; }
        public DbSet<StaffArticleFile> StaffArticleFiles { get; set; }
        public DbSet<StaffArticleFileTranslation> StaffArticleFileTranslations { get; set; }
        public DbSet<AnnualReport> AnnualReports { get; set; }
        public DbSet<AnnualReportTranslation> AnnualReportTranslations { get; set; }
        public DbSet<FinancialFlow> FinancialFlows { get; set; }
        public DbSet<FinancialFlowTranslation> FinancialFlowTranslations { get; set; }
        public DbSet<MicrofinanceModel> MicrofinanceModels { get; set; }
        public DbSet<MicrofinanceModelTranslation> MicrofinanceModelTranslations { get; set; }
        public DbSet<CybersecurityStrategy> CybersecurityStrategies { get; set; }
        public DbSet<CybersecurityStrategyTranslation> CybersecurityStrategyTranslations { get; set; }
        public DbSet<PolicyConcept> PolicyConcepts { get; set; }
        public DbSet<PolicyConceptTranslation> PolicyConceptTranslations { get; set; }
        public DbSet<RoadmapOverview> RoadmapOverviews { get; set; }
        public DbSet<RoadmapOverviewTranslation> RoadmapOverviewTranslations { get; set; }
        public DbSet<MeasAbout> MeasAbouts { get; set; }
        public DbSet<MeasAboutTranslation> MeasAboutTranslations { get; set; }
        public DbSet<MeasFile> MeasFiles { get; set; }
        public DbSet<MeasFileTranslation> MeasFileTranslations { get; set; }
        public DbSet<IssuerType> IssuerTypes { get; set; }
        public DbSet<IssuerTypeTranslation> IssuerTypeTranslations { get; set; }
        public DbSet<InformationType> InformationTypes { get; set; }
        public DbSet<InformationTypeTranslation> InformationTypeTranslations { get; set; }
        public DbSet<SecurityType> SecurityTypes { get; set; }
        public DbSet<SecurityTypeTranslation> SecurityTypeTranslations { get; set; }
        public DbSet<Meas> Meas { get; set; }
        public DbSet<MeasTranslation> MeasTranslations { get; set; }
        public DbSet<MacroEconomy> MacroEconomies { get; set; }
        public DbSet<MacroEconomyTranslation> MacroEconomyTranslations { get; set; }
        public DbSet<MonetaryStatistic> MonetaryStatistics { get; set; }
        public DbSet<MonetaryStatisticTranslation> MonetaryStatisticTranslations { get; set; }
        public DbSet<ExternalSection> ExternalSections { get; set; }
        public DbSet<ExternalSectionTranslation> ExternalSectionTranslations { get; set; }
        public DbSet<PaymentStatistic> PaymentStatistics { get; set; }
        public DbSet<PaymentStatisticTranslation> PaymentStatisticTranslations { get; set; }
        public DbSet<StatisticalReportCategory> StatisticalReportCategories { get; set; }
        public DbSet<StatisticalReportCategoryTranslation> StatisticalReportCategoryTranslations { get; set; }
        public DbSet<StatisticalReportSubCategory> StatisticalReportSubCategories { get; set; }
        public DbSet<StatisticalReportSubCategoryTranslation> StatisticalReportSubCategoryTranslations { get; set; }
        public DbSet<NSDP> NSDPs { get; set; }
        public DbSet<NSDPTranslation> NSDPTranslations { get; set; }
        public DbSet<CreditInstitutionCategory> CreditInstitutionCategories { get; set; }
        public DbSet<CreditInstitutionCategoryTranslation> CreditInstitutionCategoryTranslations { get; set; }
        public DbSet<CreditInstitutionSubCategory> CreditInstitutionSubCategories { get; set; }
        public DbSet<CreditInstitutionSubCategoryTranslation> CreditInstitutionSubCategoryTranslations { get; set; }
        public DbSet<CreditInstitution> CreditInstitutions { get; set; }
        public DbSet<CreditInstitutionTranslation> CreditInstitutionTranslations { get; set; }
        public DbSet<CapitalMarketCategory> CapitalMarketCategories { get; set; }
        public DbSet<CapitalMarketCategoryTranslation> CapitalMarketCategoryTranslations { get; set; }
        public DbSet<CapitalMarket> CapitalMarkets { get; set; }
        public DbSet<CapitalMarketTranslation> CapitalMarketTranslations { get; set; }
        public DbSet<CapitalMarketFile> CapitalMarketFiles { get; set; }
        public DbSet<CapitalMarketFileTranslation> CapitalMarketFileTranslations { get; set; }
        public DbSet<LegalBasis> legalBases { get; set; }
        public DbSet<LegalBasisTranslation> LegalBasisTranslations { get; set; }
        public DbSet<CreditInstitutionLaw> CreditInstitutionLaws { get; set; }
        public DbSet<CreditInstitutionLawTranslation> CreditInstitutionLawTranslations { get; set; }
        public DbSet<CreditInstitutionPresidentAct> CreditInstitutionPresidentActs { get; set; }
        public DbSet<CreditInstitutionPresidentActTranslation> CreditInstitutionPresidentActTranslations { get; set; }
        public DbSet<CreditInstitutionMinisterAct> CreditInstitutionMinisterActs { get; set; }
        public DbSet<CreditInstitutionMinisterActTranslation> CreditInstitutionMinisterActTranslations { get; set; }
        public DbSet<CreditInstitutionRight> CreditInstitutionRights { get; set; }
        public DbSet<CreditInstitutionRightTranslation> CreditInstitutionRightTranslations { get; set; }
        public DbSet<PaymentLaw> PaymentLaws { get; set; }
        public DbSet<PaymentLawTranslation> PaymentLawTranslations { get; set; }
        public DbSet<PaymentRight> PaymentRights { get; set; }
        public DbSet<PaymentRightCaption> PaymentRightCaptions { get; set; }
        public DbSet<PaymentRightCaptionTranslation> PaymentRightCaptionTranslations { get; set; }
        public DbSet<PaymentRightTranslation> PaymentRightTranslations { get; set; }
        public DbSet<CapitalMarketLaw> CapitalMarketLaws { get; set; }
        public DbSet<CapitalMarketLawTranslation> CapitalMarketLawTranslations { get; set; }
        public DbSet<CapitalMarketPresidentAct> CapitalMarketPresidentActs { get; set; }
        public DbSet<CapitalMarketPresidentActTranslation> CapitalMarketPresidentActTranslations { get; set; }
        public DbSet<CapitalMarketMinisterAct> CapitalMarketMinisterActs { get; set; }
        public DbSet<CapitalMarketMinisterActTranslation> CapitalMarketMinisterActTranslations { get; set; }
        public DbSet<CapitalMarketRight> CapitalMarketRights { get; set; }
        public DbSet<CapitalMarketRightTranslation> CapitalMarketRightTranslations { get; set; }
        public DbSet<InsurerLaw> InsurerLaws { get; set; }
        public DbSet<InsurerLawTranslation> InsurerLawTranslations { get; set; }
        public DbSet<InsurerPresidentAct> InsurerPresidentActs { get; set; }
        public DbSet<InsurerPresidentActTranslation> InsurerPresidentActTranslations { get; set; }
        public DbSet<InsurerMinisterAct> InsurerMinisterActs { get; set; }
        public DbSet<InsurerMinisterActTranslation> InsurerMinisterActTranslations { get; set; }
        public DbSet<InsurerRight> InsurerRights { get; set; }
        public DbSet<InsurerRightTranslation> InsurerRightTranslations { get; set; }
        public DbSet<CurrencyRegulationLaw> CurrencyRegulationLaws { get; set; }
        public DbSet<CurrencyRegulationLawTranslation> CurrencyRegulationLawTranslations { get; set; }
        public DbSet<CurrencyRegulationRight> CurrencyRegulationRights { get; set; }
        public DbSet<CurrencyRegulationRightTranslation> CurrencyRegulationRightTranslations { get; set; }
        public DbSet<LegalActStatistic> LegalActStatistics { get; set; }
        public DbSet<LegalActStatisticTranslation> LegalActStatisticTranslations { get; set; }
        public DbSet<LegalActStatisticCaption> LegalActStatisticCaptions { get; set; }
        public DbSet<LegalActStatisticCaptionTranslation> LegalActStatisticCaptionTranslations { get; set; }
        public DbSet<LegalActMethodology> LegalActMethodologies { get; set; }
        public DbSet<LegalActMethodologyTranslation> LegalActMethodologyTranslations { get; set; }
        public DbSet<OtherLaw> OtherLaws { get; set; }
        public DbSet<OtherLawTranslation> OtherLawTranslations { get; set; }
        public DbSet<OtherPresidentAct> OtherPresidentActs { get; set; }
        public DbSet<OtherPresidentActTranslation> OtherPresidentActTranslations { get; set; }
        public DbSet<OtherMinisterAct> OtherMinisterActs { get; set; }
        public DbSet<OtherMinisterActTranslation> OtherMinisterActTranslations { get; set; }
        public DbSet<OtherRight> OtherRights { get; set; }
        public DbSet<OtherRightTranslation> OtherRightTranslations { get; set; }
        public DbSet<CreditInstitutionRightCaption> CreditInstitutionRightCaptions { get; set; }
        public DbSet<CreditInstitutionRightCaptionTranslation> CreditInstitutionRightCaptionTranslations { get; set; }
        public DbSet<CapitalMarketRightCaption> CapitalMarketRightCaptions { get; set; }
        public DbSet<CapitalMarketRightCaptionTranslation> CapitalMarketRightCaptionTranslations { get; set; }
        public DbSet<InsurerRightCaption> InsurerRightCaptions { get; set; }
        public DbSet<InsurerRightCaptionTranslation> InsurerRightCaptionTranslations { get; set; }
        public DbSet<CurrencyRegulationRightCaption> CurrencyRegulationRightCaptions { get; set; }
        public DbSet<CurrencyRegulationRightCaptionTranslation> CurrencyRegulationRightCaptionTranslations { get; set; }
        public DbSet<OtherRightCaption> OtherRightCaptions { get; set; }
        public DbSet<OtherRightCaptionTranslation> OtherRightCaptionTranslations { get; set; }
        public DbSet<NonBankCaption> NonBankCaptions { get; set; }
        public DbSet<NonBankCaptionTranslation> NonBankCaptionTranslations { get; set; }
        public DbSet<NonBankFile> NonBankFiles { get; set; }
        public DbSet<NonBankFileTranslation> NonBankFileTranslations { get; set; }
        public DbSet<NonBank> NonBanks { get; set; }
        public DbSet<NonBankTranslation> NonBankTranslations { get; set; }
        public DbSet<InformationIssuerCaption> InformationIssuerCaptions { get; set; }
        public DbSet<InformationIssuerCaptionTranslation> InformationIssuerCaptionTranslations { get; set; }
        public DbSet<InformationIssuer> InformationIssuers { get; set; }
        public DbSet<InformationIssuerTranslation> InformationIssuerTranslations { get; set; }
        public DbSet<StockExchangeCaption> StockExchangeCaptions { get; set; }
        public DbSet<StockExchangeCaptionTranslation> StockExchangeCaptionTranslations { get; set; }
        public DbSet<StockExchangeFile> StockExchangeFiles { get; set; }
        public DbSet<StockExchangeFileTranslation> StockExchangeFileTranslations { get; set; }
        public DbSet<StockExchange> StockExchanges { get; set; }
        public DbSet<StockExchangeTranslation> StockExchangeTranslations { get; set; }
        public DbSet<DepositorySystem> DepositorySystems { get; set; }
        public DbSet<DepositorySystemTranslation> DepositorySystemTranslations { get; set; }
        public DbSet<InvestmentCompanyCaption> InvestmentCompanyCaptions { get; set; }
        public DbSet<InvestmentCompanyCaptionTranslation> InvestmentCompanyCaptionTranslations { get; set; }
        public DbSet<InvestmentCompanyFile> InvestmentCompanyFiles { get; set; }
        public DbSet<InvestmentCompanyFileTranslation> InvestmentCompanyFileTranslations { get; set; }
        public DbSet<InvestmentCompany> InvestmentCompanies { get; set; }
        public DbSet<InvestmentCompanyTranslation> InvestmentCompanyTranslations { get; set; }
        public DbSet<BankInvestmentCaption> BankInvestmentCaptions { get; set; }
        public DbSet<BankInvestmentCaptionTranslation> BankInvestmentCaptionTranslations { get; set; }
        public DbSet<BankInvestmentFile> BankInvestmentFiles { get; set; }
        public DbSet<BankInvestmentFileTranslation> BankInvestmentFileTranslations { get; set; }
        public DbSet<BankInvestment> BankInvestments { get; set; }
        public DbSet<BankInvestmentTranslation> BankInvestmentTranslations { get; set; }
        public DbSet<InvestmentSecurity> InvestmentSecurities { get; set; }
        public DbSet<InvestmentSecurityTranslation> InvestmentSecurityTranslations { get; set; }
        public DbSet<InvestmentSecurityFile> InvestmentSecurityFiles { get; set; }
        public DbSet<InvestmentSecurityFileTranslation> InvestmentSecurityFileTranslations { get; set; }
        public DbSet<ClearingHouse> ClearingHouses { get; set; }
        public DbSet<ClearingHouseTranslation> ClearingHouseTranslations { get; set; }
        public DbSet<InvestmentFundCaption> InvestmentFundCaptions { get; set; }
        public DbSet<InvestmentFundCaptionTranslation> InvestmentFundCaptionTranslations { get; set; }
        public DbSet<InvestmentFundFile> InvestmentFundFiles { get; set; }
        public DbSet<InvestmentFundFileTranslation> InvestmentFundFileTranslations { get; set; }
        public DbSet<InvestmentFund> InvestmentFunds { get; set; }
        public DbSet<InvestmentFundTranslation> InvestmentFundTranslations { get; set; }
        public DbSet<QualificationCertificateCaption> QualificationCertificateCaptions { get; set; }
        public DbSet<QualificationCertificateCaptionTranslation> QualificationCertificateCaptionTranslations { get; set; }
        public DbSet<QualificationCertificate> QualificationCertificates { get; set; }
        public DbSet<QualificationCertificateTranslation> QualificationCertificateTranslations { get; set; }
        public DbSet<InformationMemorandumCaption> InformationMemorandumCaptions { get; set; }
        public DbSet<InformationMemorandumCaptionTranslation> InformationMemorandumCaptionTranslations { get; set; }
        public DbSet<InformationMemorandum> InformationMemorandums { get; set; }
        public DbSet<InformationMemorandumTranslation> InformationMemorandumTranslations { get; set; }
        public DbSet<LicensingProcessCaption> LicensingProcessCaptions { get; set; }
        public DbSet<LicensingProcessCaptionTranslation> LicensingProcessCaptionTranslations { get; set; }
        public DbSet<LicensingProcess> LicensingProcesses { get; set; }
        public DbSet<LicensingProcessTranslation> LicensingProcessTranslations { get; set; }
        public DbSet<InsuranceBrokerCaption> InsuranceBrokerCaptions { get; set; }
        public DbSet<InsuranceBrokerCaptionTranslation> InsuranceBrokerCaptionTranslations { get; set; }
        public DbSet<InsuranceBroker> InsuranceBrokers { get; set; }
        public DbSet<InsuranceBrokerTranslation> InsuranceBrokerTranslations { get; set; }
        public DbSet<ForeignInsuranceBrokerCaption> ForeignInsuranceBrokerCaptions { get; set; }
        public DbSet<ForeignInsuranceBrokerCaptionTranslation> ForeignInsuranceBrokerCaptionTranslations { get; set; }
        public DbSet<ForeignInsuranceBroker> ForeignInsuranceBrokers { get; set; }
        public DbSet<ForeignInsuranceBrokerTranslation> ForeignInsuranceBrokerTranslations { get; set; }
        public DbSet<LossAdjusterCaption> LossAdjusterCaptions { get; set; }
        public DbSet<LossAdjusterCaptionTranslation> LossAdjusterCaptionTranslations { get; set; }
        public DbSet<LossAdjuster> LossAdjusters { get; set; }
        public DbSet<LossAdjusterTranslation> LossAdjusterTranslations { get; set; }
        public DbSet<ActuaryCaption> ActuaryCaptions { get; set; }
        public DbSet<ActuaryCaptionTranslation> ActuaryCaptionTranslations { get; set; }
        public DbSet<Actuary> Actuaries { get; set; }
        public DbSet<ActuaryTranslation> ActuaryTranslations { get; set; }
        public DbSet<Attestation> Attestations { get; set; }
        public DbSet<AttestationTranslation> AttestationTranslations { get; set; }
        public DbSet<AttestationFile> AttestationFiles { get; set; }
        public DbSet<AttestationFileTranslation> AttestationFileTranslations { get; set; }
        public DbSet<ElectronicMoneyInstitutionCaption> ElectronicMoneyInstitutionCaptions { get; set; }
        public DbSet<ElectronicMoneyInstitutionCaptionTranslation> ElectronicMoneyInstitutionCaptionTranslations { get; set; }
        public DbSet<ElectronicMoneyInstitutionFile> ElectronicMoneyInstitutionFiles { get; set; }
        public DbSet<ElectronicMoneyInstitutionFileTranslation> ElectronicMoneyInstitutionFileTranslations { get; set; }
        public DbSet<ElectronicMoneyInstitution> ElectronicMoneyInstitutions { get; set; }
        public DbSet<ElectronicMoneyInstitutionTranslation> ElectronicMoneyInstitutionTranslations { get; set; }
        public DbSet<PaymentInstitutionCaption> PaymentInstitutionCaptions { get; set; }
        public DbSet<PaymentInstitutionCaptionTranslation> PaymentInstitutionCaptionTranslations { get; set; }
        public DbSet<PaymentInstitutionFile> PaymentInstitutionFiles { get; set; }
        public DbSet<PaymentInstitutionFileTranslation> PaymentInstitutionFileTranslations { get; set; }
        public DbSet<PaymentInstitution> PaymentInstitutions { get; set; }
        public DbSet<PaymentInstitutionTranslation> PaymentInstitutionTranslations { get; set; }
        public DbSet<PaymentSystemOperationCaption> PaymentSystemOperationCaptions { get; set; }
        public DbSet<PaymentSystemOperationCaptionTranslation> PaymentSystemOperationCaptionTranslations { get; set; }
        public DbSet<PaymentSystemOperationFile> PaymentSystemOperationFiles { get; set; }
        public DbSet<PaymentSystemOperationFileTranslation> PaymentSystemOperationFileTranslations { get; set; }
        public DbSet<PaymentSystemOperation> PaymentSystemOperations { get; set; }
        public DbSet<PaymentSystemOperationTranslation> PaymentSystemOperationTranslations { get; set; }
        public DbSet<PostalCommunicationCaption> PostalCommunicationCaptions { get; set; }
        public DbSet<PostalCommunicationCaptionTranslation> PostalCommunicationCaptionTranslations { get; set; }
        public DbSet<PostalCommunication> PostalCommunications { get; set; }
        public DbSet<PostalCommunicationTranslation> PostalCommunicationTranslations { get; set; }
        public DbSet<CurrencyExchangeCaption> CurrencyExchangeCaptions { get; set; }
        public DbSet<CurrencyExchangeCaptionTranslation> CurrencyExchangeCaptionTranslations { get; set; }
        public DbSet<CurrencyExchange> CurrencyExchanges { get; set; }
        public DbSet<CurrencyExchangeTranslation> CurrencyExchangeTranslations { get; set; }
        public DbSet<InsuranceStatisticCategory> InsuranceStatisticCategories { get; set; }
        public DbSet<InsuranceStatisticCategoryTranslation> InsuranceStatisticCategoryTranslations { get; set; }
        public DbSet<InsuranceStatisticSubCategory> InsuranceStatisticSubCategories { get; set; }
        public DbSet<InsuranceStatisticSubCategoryTranslation> InsuranceStatisticSubCategoryTranslations { get; set; }
        public DbSet<InsuranceStatistic> InsuranceStatistics { get; set; }
        public DbSet<InsuranceStatisticTranslation> InsuranceStatisticTranslations { get; set; }
        public DbSet<FaqCategory> FaqCategories { get; set; }
        public DbSet<FaqCategoryTranslation> FaqCategoryTranslations { get; set; }
        public DbSet<Faq> Faqs { get; set; }
        public DbSet<FaqTranslation> FaqTranslations { get; set; }
        public DbSet<FaqVideo> FaqVideos { get; set; }
        public DbSet<FaqVideoTranslation> FaqVideoTranslations { get; set; }
        public DbSet<InfographicDisclosureCategory> InfographicDisclosureCategories { get; set; }
        public DbSet<InfographicDisclosureCategoryTranslation> InfographicDisclosureCategoryTranslations { get; set; }
        public DbSet<InfographicDisclosureFrequency> InfographicDisclosureFrequencies { get; set; }
        public DbSet<InfographicDisclosureFrequencyTranslation> InfographicDisclosureFrequencyTranslations { get; set; }
        public DbSet<InfographicDisclosure> InfographicDisclosures { get; set; }
        public DbSet<InfographicDisclosureTranslation> InfographicDisclosureTranslations { get; set; }
        public DbSet<InfographicDisclosureGraphic> InfographicDisclosureGraphics { get; set; }
        public DbSet<InfographicDisclosureGraphicTranslation> InfographicDisclosureGraphicTranslations { get; set; }
        public DbSet<CurrencyCaption> CurrencyCaptions { get; set; }
        public DbSet<CurrencyCaptionTranslation> CurrencyCaptionTranslations { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<PageTranslation> PageTranslations { get; set; }
        public DbSet<PageDetail> PageDetails { get; set; }
        public DbSet<PageDetailTranslation> PageDetailTranslations { get; set; }
        public DbSet<NationalBankNoteCaption> NationalBankNoteCaptions { get; set; }
        public DbSet<NationalBankNoteCaptionTranslation> NationalBankNoteCaptionTranslations { get; set; }
        public DbSet<Money> Money { get; set; }
        public DbSet<MoneyTranslation> MoneyTranslations { get; set; }
        public DbSet<MoneySign> MoneySigns { get; set; }
        public DbSet<MoneySignTranslation> MoneySignTranslations { get; set; }
        public DbSet<MoneySignHistory> MoneySignHistories { get; set; }
        public DbSet<MoneySignHistoryTranslation> MoneySignHistoryTranslations { get; set; }
        public DbSet<MoneySignHistoryFeature> MoneySignHistoryFeatures { get; set; }
        public DbSet<MoneySignHistoryFeatureTranslation> MoneySignHistoryFeatureTranslations { get; set; }
        public DbSet<MoneySignCharacteristic> MoneySignCharacteristics { get; set; }
        public DbSet<MoneySignCharacteristicTranslation> MoneySignCharacteristicTranslations { get; set; }
        public DbSet<MoneySignCharacteristicImage> MoneySignCharacteristicImages { get; set; }
        public DbSet<MoneySignCharacteristicImageTranslation> MoneySignCharacteristicImageTranslations { get; set; }
        public DbSet<MoneySignProtection> MoneySignProtections { get; set; }
        public DbSet<MoneySignProtectionCaption> MoneySignProtectionCaptions { get; set; }
        public DbSet<MoneySignProtectionCaptionTranslation> MoneySignProtectionCaptionTranslations { get; set; }
        public DbSet<MoneySignProtectionElement> MoneySignProtectionElements { get; set; }
        public DbSet<MoneySignProtectionElementTranslation> MoneySignProtectionElementTranslations { get; set; }
        public DbSet<MoneySignProtectionElementImage> MoneySignProtectionElementImages { get; set; }
        public DbSet<OutOfCirculationCaption> OutOfCirculationCaptions { get; set; }
        public DbSet<OutOfCirculationCaptionTranslation> OutOfCirculationCaptionTranslations { get; set; }
        public DbSet<OutOfCirculationCategory> OutOfCirculationCategories { get; set; }
        public DbSet<OutOfCirculationCategoryTranslation> OutOfCirculationCategoryTranslations { get; set; }
        public DbSet<CurrencyHistory> CurrencyHistories { get; set; }
        public DbSet<CurrencyHistoryTranslation> CurrencyHistoryTranslations { get; set; }
        public DbSet<CurrencyHistoryPrev> CurrencyHistoryPrevs { get; set; }
        public DbSet<CurrencyHistoryPrevTranslation> CurrencyHistoryPrevTranslations { get; set; }
        public DbSet<CurrencyHistoryPrevItem> CurrencyHistoryPrevItems { get; set; }
        public DbSet<CurrencyHistoryPrevItemTranslation> CurrencyHistoryPrevItemTranslations { get; set; }
        public DbSet<CurrencyHistoryPrevItemCharacteristic> CurrencyHistoryPrevItemCharacteristics { get; set; }
        public DbSet<CurrencyHistoryPrevItemCharacteristicTranslation> CurrencyHistoryPrevItemCharacteristicTranslations { get; set; }
        public DbSet<CurrencyHistoryPrevItemCharacteristicImage> CurrencyHistoryPrevItemCharacteristicImages { get; set; }
        public DbSet<CurrencyHistoryPrevItemCharacteristicImageTranslation> CurrencyHistoryPrevItemCharacteristicImageTranslations { get; set; }
        public DbSet<CurrencyHistoryNext> CurrencyHistoryNexts { get; set; }
        public DbSet<CurrencyHistoryNextTranslation> CurrencyHistoryNextTranslations { get; set; }
        public DbSet<CurrencyHistoryNextItem> CurrencyHistoryNextItems { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new RoleConfiguration());
            modelBuilder.ApplyConfiguration(new PermissionConfiguration());
            modelBuilder.ApplyConfiguration(new RolePermissionConfiguration());
            modelBuilder.ApplyConfiguration(new UserConfiguration());
            modelBuilder.ApplyConfiguration(new LanguageConfiguration());
            modelBuilder.ApplyConfiguration(new TranslateConfiguration());
        }
    }


}
